#!/bin/bash
# hooks/build
# https://docs.docker.com/docker-cloud/builds/advanced/

docker build \
  --build-arg VERSION=$DOCKER_TAG \
  --build-arg COMMIT=$SOURCE_COMMIT \
  --build-arg URL=$(git config --get remote.origin.url) \
  --build-arg DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ") \
  -f $DOCKERFILE_PATH \
  -t $IMAGE_NAME .